language: generic
os: osx

matrix:
    fast_finish: true
    include:
        - language: generic
          osx_image: xcode10
        - language: generic
          osx_image: xcode9.4

before_install:
    - brew install autoconf automake libtool pkg-config
    - brew link libtool
    - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - pip install -r requirements.txt
    - pip install Cython==0.29
    - git clone https://github.com/kivy/kivy

script:
    - ./toolchain.py build openssl kivy
    - ./toolchain.py create touchtracer $PWD/kivy/examples/touchtracer
