language: python
python: "3.5"
os: osx

matrix:
    fast_finish: true
    include:
        - language: python
          osx_image: xcode10

before_install:
    - brew install autoconf automake libtool pkg-config
    - brew link libtool
    - python -V
    - pip -V
    - python3 -V
    - pip3 -V
    - pip3 install -r requirements.txt
    - pip3 install Cython==0.26.1
    - git clone https://github.com/kivy/kivy

script:
    - ./toolchain.py build openssl kivy
    - ./toolchain.py create touchtracer $PWD/kivy/examples/touchtracer
