language: objective-c
os: osx

matrix:
    fast_finish: true
    include:
        - language: objective-c
          osx_image: xcode10

before_install:
    - brew install autoconf automake libtool pkg-config
    - brew link libtool
    - brew install python3; fi
    - virtualenv venv -p python3
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install Cython==0.26.1
    - git clone https://github.com/kivy/kivy

script:
    - ./toolchain.py build openssl kivy
    - ./toolchain.py create touchtracer $PWD/kivy/examples/touchtracer
